import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const sourcePath = resolve(root, 'src/data.json');
const packagePath = resolve(root, 'package.json');
const outDir = resolve(root, 'src/generated');

const source = JSON.parse(await readFile(sourcePath, 'utf8'));
const pkg = JSON.parse(await readFile(packagePath, 'utf8'));
const core = {};
const seasons = [];

for (const [key, value] of Object.entries(source)) {
  const match = key.match(/^season(\d+)$/);
  if (match) seasons.push({ season: Number(match[1]), episodes: value });
  else core[key] = value;
}

seasons.sort((a, b) => a.season - b.season);
const expected = Array.from({ length: 64 }, (_, index) => index + 1);
const found = seasons.map((item) => item.season);
if (JSON.stringify(found) !== JSON.stringify(expected)) {
  throw new Error(`Expected seasons 1-64, found: ${found.join(', ')}`);
}

/**
 * Fail the build early on malformed core lore. This is intentionally
 * lightweight and dependency-free: it guards the shapes that render code and
 * tests assume, so a bad hand/GPT edit to src/data.json is caught here rather
 * than at runtime.
 */
function validateCore(core) {
  const errors = [];
  const isStr = (v) => typeof v === 'string';
  const need = (cond, msg) => { if (!cond) errors.push(msg); };

  need(core.characters && typeof core.characters === 'object', 'characters map is missing');
  for (const [key, c] of Object.entries(core.characters || {})) {
    need(c && isStr(c.name) && c.name.trim(), `character "${key}" is missing a name`);
    need(c && isStr(c.subtitle), `character "${key}" is missing a subtitle`);
  }

  const rowFields = {
    topSkills: ['name', 'category', 'signature', 'rating', 'description'],
    ranks: ['rank', 'name', 'className', 'description'],
    seasonCast: ['name', 'role', 'description'],
  };
  const checkRows = (rows, label, fields) => {
    need(Array.isArray(rows), `${label} should be an array`);
    (Array.isArray(rows) ? rows : []).forEach((row, index) => {
      need(row && typeof row === 'object' && !Array.isArray(row), `${label}[${index}] must be an object (not a positional array)`);
      for (const field of fields) need(row && isStr(row[field]), `${label}[${index}] is missing string field "${field}"`);
    });
  };
  for (const [key, rows] of Object.entries(core.topSkills || {})) checkRows(rows, `topSkills.${key}`, rowFields.topSkills);
  checkRows(core.ranks, 'ranks', rowFields.ranks);
  for (const [season, rows] of Object.entries(core.seasonCast || {})) checkRows(rows, `seasonCast.${season}`, rowFields.seasonCast);

  for (const listName of ['rhenSkills', 'seraSkills']) {
    need(Array.isArray(core[listName]), `${listName} should be an array`);
    (core[listName] || []).forEach((skill, index) => {
      need(skill && isStr(skill.name) && skill.name.trim(), `${listName}[${index}] is missing a name`);
      need(skill && isStr(skill.category), `${listName}[${index}] is missing a category`);
    });
  }

  if (errors.length) throw new Error(`src/data.json failed validation:\n - ${errors.join('\n - ')}`);
}

function plainEpisodeText(value) {
  return String(value || '')
    .replace(/\[\[speaker:[^\]]+\]\]/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

validateCore(core);

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });
await writeFile(resolve(outDir, 'core.json'), `${JSON.stringify(core)}\n`);

const searchEpisodes = [];
for (const { season, episodes } of seasons) {
  if (!Array.isArray(episodes) || episodes.length === 0) throw new Error(`season${season} has no episodes`);
  await writeFile(resolve(outDir, `season-${season}.json`), `${JSON.stringify(episodes)}\n`);
  episodes.forEach((episode, index) => {
    const plain = plainEpisodeText(episode?.text);
    searchEpisodes.push({
      id: `ep-s${season}-e${index + 1}`,
      season,
      episode: index + 1,
      title: String(episode?.title || `Episode ${index + 1}`),
      excerpt: plain.slice(0, 220),
      searchText: plain.slice(0, 900),
    });
  });
}
await writeFile(resolve(outDir, 'search-index.json'), `${JSON.stringify({ episodes: searchEpisodes })}\n`);

const version = typeof pkg.version === 'string' ? pkg.version : '0.0.0';
const buildSha = (process.env.GITHUB_SHA || 'dev').slice(0, 7);
const buildMeta = `// Generated by scripts/prepare-data.mjs. Do not edit.\nexport const GENERATED_APP_VERSION: string = ${JSON.stringify(version)};\nexport const GENERATED_BUILD_SHA: string = ${JSON.stringify(buildSha)};\n`;
await writeFile(resolve(outDir, 'build-meta.ts'), buildMeta);

console.log(`Prepared core lore + ${seasons.length} independently loadable season files + ${searchEpisodes.length} searchable episode records (v${version} · ${buildSha}).`);
