import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const sourcePath = resolve(root, 'src/data.json');
const packagePath = resolve(root, 'package.json');
const outDir = resolve(root, 'src/generated');

const source = JSON.parse(await readFile(sourcePath, 'utf8'));
const pkg = JSON.parse(await readFile(packagePath, 'utf8'));
const core = {};
const seasons = [];

for (const [key, value] of Object.entries(source)) {
  const match = key.match(/^season(\d+)$/);
  if (match) seasons.push({ season: Number(match[1]), episodes: value });
  else core[key] = value;
}

seasons.sort((a, b) => a.season - b.season);
const expected = Array.from({ length: 64 }, (_, index) => index + 1);
const found = seasons.map((item) => item.season);
if (JSON.stringify(found) !== JSON.stringify(expected)) {
  throw new Error(`Expected seasons 1-64, found: ${found.join(', ')}`);
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });
await writeFile(resolve(outDir, 'core.json'), `${JSON.stringify(core)}\n`);

for (const { season, episodes } of seasons) {
  if (!Array.isArray(episodes) || episodes.length === 0) throw new Error(`season${season} has no episodes`);
  await writeFile(resolve(outDir, `season-${season}.json`), `${JSON.stringify(episodes)}\n`);
}

const version = typeof pkg.version === 'string' ? pkg.version : '0.0.0';
const buildSha = (process.env.GITHUB_SHA || 'dev').slice(0, 7);
const buildMeta = `// Generated by scripts/prepare-data.mjs. Do not edit.\nexport const GENERATED_APP_VERSION: string = ${JSON.stringify(version)};\nexport const GENERATED_BUILD_SHA: string = ${JSON.stringify(buildSha)};\n`;
await writeFile(resolve(outDir, 'build-meta.ts'), buildMeta);

console.log(`Prepared core lore + ${seasons.length} independently loadable season files (v${version} · ${buildSha}).`);
