import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const sourcePath = resolve(root, 'src/data.json');
const packagePath = resolve(root, 'package.json');
const outDir = resolve(root, 'src/generated');

const source = JSON.parse(await readFile(sourcePath, 'utf8'));
const pkg = JSON.parse(await readFile(packagePath, 'utf8'));
const core = {};
const seasons = [];

for (const [key, value] of Object.entries(source)) {
  const match = key.match(/^season(\d+)$/);
  if (match) seasons.push({ season: Number(match[1]), episodes: value });
  else core[key] = value;
}

seasons.sort((a, b) => a.season - b.season);
const expected = Array.from({ length: 64 }, (_, index) => index + 1);
const found = seasons.map((item) => item.season);
if (JSON.stringify(found) !== JSON.stringify(expected)) {
  throw new Error(`Expected seasons 1-64, found: ${found.join(', ')}`);
}

function plainEpisodeText(value) {
  return String(value || '')
    .replace(/\[\[speaker:[^\]]+\]\]/g, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

async function writeJson(name, value) {
  await writeFile(resolve(outDir, name), `${JSON.stringify(value)}\n`);
}

await rm(outDir, { recursive: true, force: true });
await mkdir(outDir, { recursive: true });

// Keep the historical full core for legacy.html and the self-contained single-file
// build. The normal React web app boots from react-core.json and requests the
// remaining feature payloads only when their lazy route/search surface opens.
await writeJson('core.json', core);
await writeJson('react-core.json', { characters: core.characters });
await writeJson('react-ranks.json', { ranks: core.ranks });
await writeJson('react-legends.json', { legends: core.legends });
await writeJson('react-season-cast.json', { seasonCast: core.seasonCast });
await writeJson('react-villains.json', { arcFigures: core.arcFigures });
await writeJson('react-techniques.json', { rhenSkills: core.rhenSkills, seraSkills: core.seraSkills });
await writeJson('react-former.json', { former: core.former });
await writeJson('react-timeline.json', { seraTimeline: core.seraTimeline });
await writeJson('react-canon.json', { canonRules: core.canonRules || [] });

const searchEpisodes = [];
for (const { season, episodes } of seasons) {
  if (!Array.isArray(episodes) || episodes.length === 0) throw new Error(`season${season} has no episodes`);
  await writeJson(`season-${season}.json`, episodes);
  episodes.forEach((episode, index) => {
    const plain = plainEpisodeText(episode?.text);
    searchEpisodes.push({
      id: `ep-s${season}-e${index + 1}`,
      season,
      episode: index + 1,
      title: String(episode?.title || `Episode ${index + 1}`),
      excerpt: plain.slice(0, 220),
      searchText: plain.slice(0, 900),
    });
  });
}
await writeJson('search-index.json', { episodes: searchEpisodes });

const version = typeof pkg.version === 'string' ? pkg.version : '0.0.0';
const buildSha = (process.env.GITHUB_SHA || 'dev').slice(0, 7);
const buildMeta = `// Generated by scripts/prepare-data.mjs. Do not edit.\nexport const GENERATED_APP_VERSION: string = ${JSON.stringify(version)};\nexport const GENERATED_BUILD_SHA: string = ${JSON.stringify(buildSha)};\n`;
await writeFile(resolve(outDir, 'build-meta.ts'), buildMeta);

console.log(`Prepared full compatibility core + split React lore + ${seasons.length} independently loadable season files + ${searchEpisodes.length} searchable episode records (v${version} · ${buildSha}).`);
